import Navbar from './navbar';
import sytlehome from './contanierHome.module.css';
export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
};

export default function ContainerHome({ children }) {
  return (
    <div className={sytlehome.home}>
      <Navbar />
      {children}
    </div>
  );
}
