import style from './user.module.css';
export const metadata = {
  title: 'User',
  description: 'Generated by Next.js',
};

export default function LayoutUser({ children }) {
  return <div className={style.layout}>{children}</div>;
}
