import '../src/app/globals.css';
import Navbar from './navbar.jsx';

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <section className='contSec'>
          <Navbar />
          {children}
        </section>
      </body>
    </html>
  );
}
