import './globals.css';
import Navbar from './(navbar)/navbar';
import '/node_modules/bootstrap-icons/font/bootstrap-icons.css';
import { AuthContextProvider } from '../contextApp/AuthContext';
import ProtectedRoute from '../protedRuteComponent/protedRute';

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <AuthContextProvider>
          <ProtectedRoute>
            <main className='contSec'>
              <Navbar />
              {children}
            </main>
          </ProtectedRoute>
        </AuthContextProvider>
      </body>
    </html>
  );
}
