import './globals.css';
import '/node_modules/bootstrap-icons/font/bootstrap-icons.css';
import { lato } from './fonts';
import Providers from './Provider';

export const metadata = {
  title: 'TBT-App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={lato.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
