import style from './sing.module.css';

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return <div className={style.container}>{children}</div>;
}
